version: '3.10'

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

services:
  chat_app:
    container_name: chat_app
    hostname: chat_app
    image: registry.tuoitre.vn/services/chat_app:v1
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - APP_PORT=${APP_PORT}
    ports:
      - "5000:5000"
    volumes:
      - ../flask-chat:/app
    networks:
      - mynetwork
    dns:
      - 8.8.8.8
